version: "3.8"
services:
  client:
    build:
      dockerfile: examples/bridge/client/Dockerfile
      context: ../..
    environment:
      - WAIT_HOSTS=cloud:4840,plc:4840
  cloud:
    build:
      dockerfile: examples/bridge/cloud/Dockerfile
      context: ../..
    expose:
      - 4840
    environment:
      - OPC_PLC_URL=opc.tcp://plc:4840
      - WAIT_HOSTS=plc:4840
    ports:
      - '4839:4840'
  plc:
    build:
      dockerfile: examples/bridge/PLC/Dockerfile
      context: ../..
    expose:
      - 4840
    ports:
      - '4841:4840'
