version: "3.8"
services:
  client:
    build:
      dockerfile: examples/bridge/client/Dockerfile
      context: ../..
    environment:
      - WAIT_HOSTS=cloud:4840,plc:4840
      - WAIT_HOSTS_TIMEOUT=90
  cloud:
    build:
      dockerfile: examples/bridge/cloud/yaml-test.Dockerfile
      context: ../..
    expose:
      - 4840
    environment:
      - OPC_PLC_URL=opc.tcp://plc:4840
      - secure=true
      #- OPC_PLC_URL_2=opc.tcp://plc2:4840
      - WAIT_HOSTS=plc:4840 #,plc2:4840
    ports:
      - '4839:4840'
    volumes:
      - './test_yaml:/appdata/test_yaml'
  plc:
    build:
      dockerfile: examples/bridge/PLC/Dockerfile
      context: ../..
    expose:
      - 4840
    ports:
      - '4841:4840'
#  plc2:
#    image: mcr.microsoft.com/iotedge/opc-plc
#    command: --pn 4840 --autoaccept --ut
#    restart: on-failure
#    expose:
#      - 4840