version: "3.8"
services:
  client:
    build:
      dockerfile: client/Dockerfile
      context: .
    environment:
      - WAIT_HOSTS=cloud:4840,plc:4840
  cloud:
    build:
      dockerfile: cloud/Dockerfile
      context: .
    expose:
      - 4840
    environment:
      - WAIT_HOSTS=plc:4840
    ports:
      - '4839:4840'
  plc:
    build:
      dockerfile: PLC/Dockerfile
      context: .
    expose:
      - 4840
    ports:
      - '4840:4840'
