version: "3.8"
services:
  client:
    build:
      dockerfile: examples/bridge/client/Dockerfile
      context: ../..
    environment:
      - WAIT_HOSTS=cloud:4840,plc:4840
  cloud:
    build:
      dockerfile: examples/bridge/cloud/reliability-test.Dockerfile
      context: ../..
    expose:
      - 4840
    environment:
      - OPC_PLC_URL=opc.tcp://plc:4840
      - WAIT_HOSTS=plc:4840
    restart: on-failure
    ports:
      - '4839:4840'
    volumes:
      - './test_yaml:/appdata/test_yaml'
  plc:
    build:
      dockerfile: examples/bridge/PLC/interrupted_process.Dockerfile
      context: ../..
    expose:
      - 4840
    ports:
      - '4841:4840'
    restart: on-failure

#  plc2:
#    image: mcr.microsoft.com/iotedge/opc-plc
#    command: --pn 4840 --autoaccept --ut
#    restart: on-failure
#    expose:
#      - 4840